### ISSUE TITLE
after pip3 install, unittests fail 

### ISSUE THREAD

**Issue by tseemann** [schultzm/gnb#1]
```
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/gnb/tests/gnb_test.py", line 43, in merger
    ncbiup     = Table(self.NCBIup).ncbi_template()
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/gnb/utils/table_maker.py", line 14, in ncbi_template
    df = pd.read_excel(self.indata, skiprows=12)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 824, in __init__
    self._reader = self._engines[engine](self._io)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py", line 21, in __init__
    super().__init__(filepath_or_buffer)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 353, in __init__
    self.book = self.load_workbook(filepath_or_buffer)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py", line 36, in load_workbook
    return open_workbook(filepath_or_buffer)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/xlrd/__init__.py", line 111, in open_workbook
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/gnb/data/NCBI_BiosampleBuilder.xlsx'

----------------------------------------------------------------------
Ran 5 tests in 0.019s

FAILED (errors=4)

```

**Comment by schultzm** [comment]
Fixed.
